import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {root,listSkins,manifestAt,validateManifest,validateSources,sums,packageFiles} from '../scripts/lib.mjs';
for(const id of listSkins())test(id+': build reproducible, inventory exact',()=>{const dir=path.join(root,'dist',id),m=manifestAt(dir),before=sums(dir,['skin.json',...m.files]);assert.equal(spawnSync(process.execPath,['scripts/build.mjs',id],{cwd:root}).status,0);assert.equal(sums(dir,['skin.json',...m.files]),before);assert.deepEqual(packageFiles(dir),['skin.json',...m.files].sort());assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'skins',id,'skin.json'))),m);});
const good=()=>structuredClone(manifestAt(path.join(root,'skins','holonet')));
for(const[key,mutate]of Object.entries({reserved_id:m=>m.id='comic',reserved_name:m=>m.name='  ClAsSiC  ',unsupported_api:m=>m.api=2,duplicate_file:m=>m.files.push(m.files[0]),traversal:m=>m.files.push('../leak.mjs'),undeclared_entry:m=>m.entry='other.mjs',external_file:m=>m.files.push('https://bad.test/x.mjs'),too_many_files:m=>m.files=Array.from({length:33},(_,i)=>i+'.mjs'),manifest_trust:m=>m.builtin=true}))test('reject '+key,()=>{const m=good();mutate(m);assert.throws(()=>validateManifest(m));});
for(const[key,code]of Object.entries({direct_api:'fetch("/api/overview")',private_globals:'window.agentnet.api()',polling:'setInterval(()=>{},100)',outside_dom:'document.body.append("x")',undeclared_import:'import "x" from "./missing.mjs"',inline_style:'const attrs={style:"display:none"}',native_clipboard:'window.agentnet.clipboard()'}))test('reject '+key,()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'skin-negative-'));try{fs.writeFileSync(path.join(dir,'entry.mjs'),code);assert.throws(()=>validateSources(dir,{files:['entry.mjs']}));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('reject symlink',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'skin-negative-'));try{fs.writeFileSync(path.join(dir,'real.mjs'),'');fs.symlinkSync('real.mjs',path.join(dir,'entry.mjs'));assert.throws(()=>validateSources(dir,{files:['entry.mjs']}));}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('reject symlink ancestor',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'skin-negative-'));try{fs.mkdirSync(path.join(dir,'real'));fs.writeFileSync(path.join(dir,'real/entry.mjs'),'');fs.symlinkSync('real',path.join(dir,'assets'));assert.throws(()=>validateSources(dir,{files:['assets/entry.mjs']}));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('reject unquoted external CSS asset',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'skin-negative-'));try{fs.writeFileSync(path.join(dir,'style.css'),'p { background:url(https://bad.test/p.png) }');assert.throws(()=>validateSources(dir,{files:['style.css']}));}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('nested declared assets build with exact recursive inventory',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'skin-nested-'));try{fs.cpSync(path.join(root,'scripts'),path.join(temp,'scripts'),{recursive:true});const skin=path.join(temp,'skins','nested'),source=path.join(skin,'src');fs.mkdirSync(path.join(source,'fonts'),{recursive:true});const m={api:1,id:'nested',name:'Nested',entry:'entry.mjs',files:['entry.mjs','fonts/console.woff2']};fs.writeFileSync(path.join(skin,'skin.json'),JSON.stringify(m));fs.writeFileSync(path.join(source,'entry.mjs'),'export async function mount() { return { unmount() {} }; }');fs.writeFileSync(path.join(source,'fonts/console.woff2'),'wOF2');const x=spawnSync(process.execPath,['scripts/build.mjs'],{cwd:temp,encoding:'utf8'});assert.equal(x.status,0,x.stderr);const output=path.join(temp,'dist','nested');assert.deepEqual(packageFiles(output),['skin.json',...m.files].sort());fs.writeFileSync(path.join(output,'fonts','unexpected.json'),'{}');assert.notDeepEqual(packageFiles(output),['skin.json',...m.files].sort(),'Nested undeclared files are visible to the inventory check');}finally{fs.rmSync(temp,{recursive:true,force:true});}});
