import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {root,listSkins,manifestAt,validateManifest,validateSources,sums} from '../scripts/lib.mjs';
for(const id of listSkins())test(id+': build reproducible, inventory exact',()=>{const dir=path.join(root,'dist',id),m=manifestAt(dir),before=sums(dir,['skin.json',...m.files]);assert.equal(spawnSync(process.execPath,['scripts/build.mjs',id],{cwd:root}).status,0);assert.equal(sums(dir,['skin.json',...m.files]),before);assert.equal(fs.readdirSync(dir).length,m.files.length+1);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'skins',id,'skin.json'))),m);});
const good=()=>structuredClone(manifestAt(path.join(root,'skins','holonet')));
for(const[key,mutate]of Object.entries({reserved_id:m=>m.id='comic',reserved_name:m=>m.name='  ClAsSiC  ',unsupported_api:m=>m.api=2,duplicate_file:m=>m.files.push(m.files[0]),traversal:m=>m.files.push('../leak.mjs'),undeclared_entry:m=>m.entry='other.mjs',external_file:m=>m.files.push('https://bad.test/x.mjs'),too_many_files:m=>m.files=Array.from({length:33},(_,i)=>i+'.mjs'),manifest_trust:m=>m.builtin=true}))test('reject '+key,()=>{const m=good();mutate(m);assert.throws(()=>validateManifest(m));});
for(const[key,code]of Object.entries({direct_api:'fetch("/api/overview")',private_globals:'window.agentnet.api()',polling:'setInterval(()=>{},100)',outside_dom:'document.body.append("x")',undeclared_import:'import "x" from "./missing.mjs"',inline_style:'const attrs={style:"display:none"}',native_clipboard:'window.agentnet.clipboard()'}))test('reject '+key,()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'skin-negative-'));try{fs.writeFileSync(path.join(dir,'entry.mjs'),code);assert.throws(()=>validateSources(dir,{files:['entry.mjs']}));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('reject symlink',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'skin-negative-'));try{fs.writeFileSync(path.join(dir,'real.mjs'),'');fs.symlinkSync('real.mjs',path.join(dir,'entry.mjs'));assert.throws(()=>validateSources(dir,{files:['entry.mjs']}));}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('reject symlink ancestor',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'skin-negative-'));try{fs.mkdirSync(path.join(dir,'real'));fs.writeFileSync(path.join(dir,'real/entry.mjs'),'');fs.symlinkSync('real',path.join(dir,'assets'));assert.throws(()=>validateSources(dir,{files:['assets/entry.mjs']}));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('reject unquoted external CSS asset',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'skin-negative-'));try{fs.writeFileSync(path.join(dir,'style.css'),'p { background:url(https://bad.test/p.png) }');assert.throws(()=>validateSources(dir,{files:['style.css']}));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
